INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Yadav", "SE Marsh", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Yadav", "SE Marsh", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Yadav", "SE Marsh", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Yadav", "SE Marsh", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Yadav", "SE Marsh", 4, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Yadav", "SE Marsh", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Sran", "Finch", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Sran", "SE Marsh", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Sran", "SE Marsh", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Sran", "Finch", 1, 1, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Sran", "Finch", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Sran", "Finch", 4, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Sran", "Finch", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Yadav", "SE Marsh", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Yadav", "SE Marsh", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Yadav", "SE Marsh", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Yadav", "Finch", 3, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Yadav", "SE Marsh", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Yadav", "SE Marsh", 4, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Sran", "Finch", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Sran", "Finch", 2, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Sran", "Finch", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Sran", "Finch", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Sran", "SE Marsh", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Sran", "SE Marsh", 4, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("I Sharma", "Finch", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("I Sharma", "Finch", 1, 1, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("I Sharma", "Finch", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("I Sharma", "SE Marsh", 3, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("I Sharma", "Finch", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("I Sharma", "Finch", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("I Sharma", "Finch", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Sran", "SE Marsh", 3, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Sran", "Finch", 4, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Sran", "Finch", 4, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Sran", "Finch", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Sran", "Finch", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Sran", "Finch", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("I Sharma", "SE Marsh", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("I Sharma", "Finch", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("I Sharma", "Finch", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("I Sharma", "Finch", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("I Sharma", "SE Marsh", 4, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("I Sharma", "SE Marsh", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Yadav", "Finch", 0, 0, 0, 0, 1);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Yadav", "Smith", 1, 1, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Yadav", "Smith", 2, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Yadav", "Smith", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Yadav", "Smith", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Yadav", "Smith", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Yadav", "SE Marsh", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("I Sharma", "Smith", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("I Sharma", "Smith", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("I Sharma", "Smith", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("I Sharma", "Smith", 4, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("I Sharma", "Smith", 4, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("I Sharma", "Smith", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Yadav", "SE Marsh", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Yadav", "SE Marsh", 1, 0, 0, 1, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Yadav", "Smith", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Yadav", "Smith", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Yadav", "Smith", 4, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Yadav", "Smith", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("R Dhawan", "SE Marsh", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("R Dhawan", "SE Marsh", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("R Dhawan", "SE Marsh", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("R Dhawan", "SE Marsh", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("R Dhawan", "SE Marsh", 2, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("R Dhawan", "SE Marsh", 2, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Yadav", "Smith", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Yadav", "SE Marsh", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Yadav", "Smith", 2, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Yadav", "Smith", 3, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Yadav", "SE Marsh", 2, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Yadav", "SE Marsh", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("R Dhawan", "Smith", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("R Dhawan", "SE Marsh", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("R Dhawan", "SE Marsh", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("R Dhawan", "SE Marsh", 2, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("R Dhawan", "SE Marsh", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("R Dhawan", "Smith", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Gurkeerat Singh", "Smith", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Gurkeerat Singh", "SE Marsh", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Gurkeerat Singh", "Smith", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Gurkeerat Singh", "Smith", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Gurkeerat Singh", "Smith", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Gurkeerat Singh", "SE Marsh", 4, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("R Dhawan", "Smith", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("R Dhawan", "Smith", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("R Dhawan", "Smith", 4, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("R Dhawan", "Smith", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("R Dhawan", "Smith", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("R Dhawan", "Smith", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Gurkeerat Singh", "Smith", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Gurkeerat Singh", "Smith", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Gurkeerat Singh", "Smith", 4, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Gurkeerat Singh", "Smith", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Gurkeerat Singh", "Smith", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Gurkeerat Singh", "SE Marsh", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("R Dhawan", "Smith", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("R Dhawan", "Smith", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("R Dhawan", "Smith", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("R Dhawan", "Smith", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("R Dhawan", "Smith", 2, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("R Dhawan", "Smith", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Gurkeerat Singh", "Smith", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Gurkeerat Singh", "SE Marsh", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Gurkeerat Singh", "SE Marsh", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Gurkeerat Singh", "SE Marsh", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Gurkeerat Singh", "SE Marsh", 3, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Gurkeerat Singh", "Smith", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Jadeja", "Smith", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Jadeja", "Smith", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Jadeja", "SE Marsh", 2, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Jadeja", "SE Marsh", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Jadeja", "Smith", 0, 0, 0, 0, 1);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Jadeja", "Bailey", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Gurkeerat Singh", "Bailey", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Gurkeerat Singh", "SE Marsh", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Gurkeerat Singh", "SE Marsh", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Gurkeerat Singh", "Bailey", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Gurkeerat Singh", "SE Marsh", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Gurkeerat Singh", "Bailey", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Jadeja", "Bailey", 4, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Jadeja", "Bailey", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Jadeja", "SE Marsh", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Jadeja", "SE Marsh", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Jadeja", "SE Marsh", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Jadeja", "Bailey", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("R Dhawan", "SE Marsh", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("R Dhawan", "SE Marsh", 2, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("R Dhawan", "SE Marsh", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("R Dhawan", "SE Marsh", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("R Dhawan", "Bailey", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("R Dhawan", "Bailey", 4, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Jadeja", "SE Marsh", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Jadeja", "SE Marsh", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Jadeja", "SE Marsh", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Jadeja", "Bailey", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Jadeja", "Bailey", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Jadeja", "SE Marsh", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("R Dhawan", "Bailey", 4, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("R Dhawan", "Bailey", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("R Dhawan", "Bailey", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("R Dhawan", "SE Marsh", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("R Dhawan", "SE Marsh", 4, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("R Dhawan", "SE Marsh", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Jadeja", "Bailey", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Jadeja", "Bailey", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Jadeja", "SE Marsh", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Jadeja", "SE Marsh", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Jadeja", "SE Marsh", 2, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Jadeja", "SE Marsh", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Gurkeerat Singh", "Bailey", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Gurkeerat Singh", "SE Marsh", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Gurkeerat Singh", "Bailey", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Gurkeerat Singh", "SE Marsh", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Gurkeerat Singh", "Bailey", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Gurkeerat Singh", "Bailey", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Jadeja", "Bailey", 0, 0, 0, 0, 1);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Jadeja", "Maxwell", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Jadeja", "Maxwell", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Jadeja", "Maxwell", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Jadeja", "Maxwell", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Jadeja", "Maxwell", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("I Sharma", "Maxwell", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("I Sharma", "Maxwell", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("I Sharma", "Maxwell", 2, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("I Sharma", "Maxwell", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("I Sharma", "SE Marsh", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("I Sharma", "SE Marsh", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Jadeja", "Maxwell", 4, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Jadeja", "Maxwell", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Jadeja", "Maxwell", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Jadeja", "Maxwell", 1, 1, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Jadeja", "Maxwell", 2, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Jadeja", "Maxwell", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Jadeja", "Maxwell", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("I Sharma", "Maxwell", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("I Sharma", "SE Marsh", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("I Sharma", "SE Marsh", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("I Sharma", "Maxwell", 2, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("I Sharma", "Maxwell", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("I Sharma", "SE Marsh", 0, 0, 0, 0, 1);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Sran", "Maxwell", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Sran", "MR Marsh", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Sran", "MR Marsh", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Sran", "Maxwell", 4, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Sran", "Maxwell", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Sran", "MR Marsh", 4, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("I Sharma", "Maxwell", 4, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("I Sharma", "Maxwell", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("I Sharma", "Maxwell", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("I Sharma", "MR Marsh", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("I Sharma", "MR Marsh", 1, 0, 0, 1, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("I Sharma", "Maxwell", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Yadav", "Maxwell", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Yadav", "Maxwell", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Yadav", "MR Marsh", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Yadav", "MR Marsh", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Yadav", "MR Marsh", 4, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Yadav", "MR Marsh", 4, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Sran", "Maxwell", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Sran", "Maxwell", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Sran", "Maxwell", 2, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Sran", "Maxwell", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Sran", "MR Marsh", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Sran", "MR Marsh", 2, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Yadav", "Maxwell", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Yadav", "Maxwell", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Yadav", "Maxwell", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Yadav", "MR Marsh", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Yadav", "MR Marsh", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Yadav", "MR Marsh", 2, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Sran", "Maxwell", 2, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Sran", "Wade", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Sran", "Maxwell", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Sran", "Wade", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Sran", "Wade", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Sran", "Wade", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("I Sharma", "Maxwell", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("I Sharma", "Wade", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("I Sharma", "Maxwell", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("I Sharma", "Wade", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("I Sharma", "Maxwell", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("I Sharma", "Maxwell", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Sran", "Wade", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Sran", "Maxwell", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Sran", "Maxwell", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Sran", "Wade", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Sran", "Maxwell", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Sran", "Wade", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("I Sharma", "Wade", 0, 0, 0, 0, 1);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("I Sharma", "Maxwell", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("I Sharma", "Faulkner", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("I Sharma", "Faulkner", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("I Sharma", "Maxwell", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("I Sharma", "Maxwell", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Sran", "Maxwell", 4, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Sran", "Maxwell", 2, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Sran", "Maxwell", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Sran", "Maxwell", 1, 1, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Sran", "Maxwell", 6, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Sran", "Maxwell", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Sran", "Maxwell", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Yadav", "Faulkner", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Yadav", "Faulkner", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Yadav", "Maxwell", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Yadav", "Maxwell", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Yadav", "Maxwell", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Yadav", "Maxwell", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Jadeja", "Faulkner", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Jadeja", "Maxwell", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Jadeja", "Faulkner", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Jadeja", "Maxwell", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Jadeja", "Faulkner", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Jadeja", "Faulkner", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Yadav", "Faulkner", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Yadav", "Faulkner", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Yadav", "Faulkner", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Yadav", "Maxwell", 6, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Yadav", "Maxwell", 2, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Yadav", "Maxwell", 4, 0, 1, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Yadav", "Maxwell", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Jadeja", "Maxwell", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Jadeja", "Maxwell", 2, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Jadeja", "Maxwell", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Jadeja", "Faulkner", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Jadeja", "Maxwell", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Jadeja", "Maxwell", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("I Sharma", "Maxwell", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("I Sharma", "Faulkner", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("I Sharma", "Maxwell", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("I Sharma", "Maxwell", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("I Sharma", "Maxwell", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("I Sharma", "Faulkner", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Jadeja", "Faulkner", 4, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Jadeja", "Faulkner", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Jadeja", "Maxwell", 4, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Jadeja", "Maxwell", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Jadeja", "Maxwell", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Jadeja", "Maxwell", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("I Sharma", "Maxwell", 4, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("I Sharma", "Maxwell", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("I Sharma", "Faulkner", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("I Sharma", "Faulkner", 2, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("I Sharma", "Faulkner", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("I Sharma", "Faulkner", 2, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Jadeja", "Maxwell", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Jadeja", "Faulkner", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Jadeja", "Faulkner", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Jadeja", "Faulkner", 2, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Jadeja", "Faulkner", 1, 0, 0, 1, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Jadeja", "Maxwell", 1, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Yadav", "Maxwell", 0, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Yadav", "Maxwell", 6, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Yadav", "Maxwell", 4, 0, 0, 0, 0);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Yadav", "Maxwell", 0, 0, 0, 0, 1);
INSERT INTO Australia(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Yadav", "Faulkner", 1, 0, 0, 0, 0);
