CREATE TABLE Match_Details (ODI_NO INT PRIMARY KEY NOT NULL,
	Stadium VARCHAR(50) NOT NULL,
	Match_Date VARCHAR(10) NOT NULL,
	Wickets_Left INT NOT NULL,
	Balls_Left INT NOT NULL);
	
CREATE TABLE Match_Umpires (ODI_NO INT,
	FOREIGN KEY (ODI_NO) REFERENCES Match_Details(ODI_NO),
	Umpire_Name VARCHAR(50) NOT NULL,
	Ground TINYINT(1) NOT NULL,
	TV TINYINT(1) NOT NULL,
	Refree TINYINT(1) NOT NULL,
	Reserve TINYINT(1) NOT NULL);

CREATE TABLE Team (TID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	ODI_NO INT,
	FOREIGN KEY(ODI_NO) REFERENCES Match_Details(ODI_NO),
	Team_Name VARCHAR(50) NOT NULL,
	Score INT NOT NULL DEFAULT 0,
	Against VARCHAR(50) NOT NULL,
	RPO DOUBLE NOT NULL DEFAULT 0.0,
	Wickets_Fall INT NOT NULL DEFAULT 0,
	Minutes INT NOT NULL,
	lb INT NOT NULL DEFAULT 0,
	nb INT NOT NULL DEFAULT 0,
	Wide INT NOT NULL DEFAULT 0,
	Toss TINYINT(1) NOT NULL,
	Won TINYINT(1) NOT NULL);

CREATE TABLE Player (PID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	TID INT,
	FOREIGN KEY (TID) REFERENCES Team(TID),
	Player_Name VARCHAR(50) NOT NULL,
	Debute TINYINT(1) NOT NULL,
	Bat TINYINT(1) NOT NULL,
	Bowl TINYINT(1) NOT NULL);

CREATE TABLE Batting (PID INT,
	FOREIGN KEY (PID) REFERENCES Player(PID),
	R INT,
	M INT,
	B INT,
	4s INT,
	6s INT,
	SR DOUBLE,
	CB INT,
	BB INT,
	ST INT,
	RO INT,
	Out_Over DOUBLE,
	Score INT);
	
CREATE TABLE Bowling (PID INT,
	FOREIGN KEY (PID) REFERENCES Player(PID),
	O DOUBLE NOT NULL,
	M INT NOT NULL,
	R INT NOT NULL,
	W INT NOT NULL,
	Econ DOUBLE NOT NULL,
	0s INT NOT NULL,
	4s INT NOT NULL,
	6s INT NOT NULL,
	Wide INT NOT NULL,
	lb INT NOT NULL,
	nb INT NOT NULL);
	
CREATE TABLE Judged_By (ODI_NO INT,
	PRIMARY KEY (ODI_NO),
	FOREIGN KEY (ODI_NO) REFERENCES Match_Details(ODI_NO),
	FOREIGN KEY (ODI_NO) REFERENCES Match_Umpires(ODI_NO));
	
CREATE TABLE Played_By (ODI_NO INT,
	TID INT,
	PRIMARY KEY (TID, ODI_NO),
	FOREIGN KEY (ODI_NO) REFERENCES Match_Details(ODI_NO),
	FOREIGN KEY (TID) REFERENCES Team(TID));
	
CREATE TABLE Of (TID INT,
	PID INT,
	PRIMARY KEY (TID, PID),
	FOREIGN KEY (TID) REFERENCES Team(TID),
	FOREIGN KEY (PID) REFERENCES Player(PID));
	
CREATE TABLE Bat_Details (PID INT,
	PRIMARY KEY (PID),
	FOREIGN KEY (PID) REFERENCES Batting(PID),
	FOREIGN KEY (PID) REFERENCES Player(PID));
	
CREATE TABLE Bowl_Details (PID INT,
	PRIMARY KEY (PID),
	FOREIGN KEY (PID) REFERENCES Bowling(PID),
	FOREIGN KEY (PID) REFERENCES Player(PID));
