CREATE TABLE India(ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,Bowler VARCHAR(50) NOT NULL,Batsman VARCHAR(50) NOT NULL,Runs INT NOT NULL,Wide TINYINT(1),No_Ball TINYINT(1), Leg_Bye TINYINT(1), Wicket TINYINT(1));
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Richardson", "RG Sharma", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Richardson", "RG Sharma", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Richardson", "RG Sharma", 2, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Richardson", "RG Sharma", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Richardson", "S Dhawan", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Richardson", "S Dhawan", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Hastings", "RG Sharma", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Hastings", "S Dhawan", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Hastings", "S Dhawan", 1, 1, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Hastings", "S Dhawan", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Hastings", "S Dhawan", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Hastings", "S Dhawan", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Hastings", "S Dhawan", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Richardson", "RG Sharma", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Richardson", "RG Sharma", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Richardson", "S Dhawan", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Richardson", "S Dhawan", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Richardson", "S Dhawan", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Richardson", "S Dhawan", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Hastings", "RG Sharma", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Hastings", "S Dhawan", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Hastings", "S Dhawan", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Hastings", "S Dhawan", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Hastings", "S Dhawan", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Hastings", "S Dhawan", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Richardson", "RG Sharma", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Richardson", "RG Sharma", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Richardson", "RG Sharma", 0, 0, 0, 0, 1);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Richardson", "Kohli", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Richardson", "S Dhawan", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Richardson", "S Dhawan", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Hastings", "Kohli", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Hastings", "Kohli", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Hastings", "Kohli", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Hastings", "Kohli", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Hastings", "S Dhawan", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Hastings", "S Dhawan", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Richardson", "Kohli", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Richardson", "S Dhawan", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Richardson", "S Dhawan", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Richardson", "Kohli", 1, 1, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Richardson", "Kohli", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Richardson", "Kohli", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Richardson", "S Dhawan", 1, 0, 0, 1, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Hastings", "S Dhawan", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Hastings", "Kohli", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Hastings", "Kohli", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Hastings", "Kohli", 3, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Hastings", "S Dhawan", 2, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Hastings", "S Dhawan", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Richardson", "Kohli", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Richardson", "Kohli", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Richardson", "Kohli", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Richardson", "Kohli", 3, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Richardson", "S Dhawan", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Richardson", "S Dhawan", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Faulkner", "Kohli", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Faulkner", "S Dhawan", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Faulkner", "Kohli", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Faulkner", "S Dhawan", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Faulkner", "Kohli", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Faulkner", "Kohli", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Boland", "S Dhawan", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Boland", "S Dhawan", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Boland", "Kohli", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Boland", "Kohli", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Boland", "Kohli", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Boland", "S Dhawan", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Faulkner", "S Dhawan", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Faulkner", "S Dhawan", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Faulkner", "S Dhawan", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Faulkner", "S Dhawan", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Faulkner", "Kohli", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Faulkner", "Kohli", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Maxwell", "S Dhawan", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Maxwell", "S Dhawan", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Maxwell", "Kohli", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Maxwell", "S Dhawan", 2, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Maxwell", "S Dhawan", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Maxwell", "Kohli", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Faulkner", "S Dhawan", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Faulkner", "S Dhawan", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Faulkner", "S Dhawan", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Faulkner", "S Dhawan", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Faulkner", "S Dhawan", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Faulkner", "Kohli", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Maxwell", "Kohli", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Maxwell", "S Dhawan", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Maxwell", "Kohli", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Maxwell", "Kohli", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Maxwell", "S Dhawan", 1, 0, 0, 1, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Maxwell", "Kohli", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Faulkner", "S Dhawan", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Faulkner", "Kohli", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Faulkner", "S Dhawan", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Faulkner", "Kohli", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Faulkner", "S Dhawan", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Faulkner", "S Dhawan", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Maxwell", "S Dhawan", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Maxwell", "S Dhawan", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Maxwell", "S Dhawan", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Maxwell", "Kohli", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Maxwell", "S Dhawan", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Maxwell", "Kohli", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Boland", "Kohli", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Boland", "S Dhawan", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Boland", "S Dhawan", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Boland", "S Dhawan", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Boland", "S Dhawan", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Boland", "S Dhawan", 1, 1, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Boland", "S Dhawan", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("MR Marsh", "Kohli", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("MR Marsh", "S Dhawan", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("MR Marsh", "S Dhawan", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("MR Marsh", "S Dhawan", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("MR Marsh", "Kohli", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("MR Marsh", "S Dhawan", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Boland", "Kohli", 2, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Boland", "Kohli", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Boland", "S Dhawan", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Boland", "Kohli", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Boland", "Kohli", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Boland", "S Dhawan", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("MR Marsh", "Kohli", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("MR Marsh", "Kohli", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("MR Marsh", "S Dhawan", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("MR Marsh", "S Dhawan", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("MR Marsh", "S Dhawan", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("MR Marsh", "S Dhawan", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Boland", "Kohli", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Boland", "Kohli", 2, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Boland", "Kohli", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Boland", "Kohli", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Boland", "Kohli", 2, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Boland", "Kohli", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Maxwell", "S Dhawan", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Maxwell", "S Dhawan", 2, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Maxwell", "S Dhawan", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Maxwell", "S Dhawan", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Maxwell", "Kohli", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Maxwell", "S Dhawan", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Richardson", "S Dhawan", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Richardson", "Kohli", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Richardson", "Kohli", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Richardson", "S Dhawan", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Richardson", "S Dhawan", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Richardson", "Kohli", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Maxwell", "S Dhawan", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Maxwell", "S Dhawan", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Maxwell", "S Dhawan", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Maxwell", "S Dhawan", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Maxwell", "Kohli", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Maxwell", "Kohli", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Richardson", "S Dhawan", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Richardson", "Kohli", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Richardson", "S Dhawan", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Richardson", "S Dhawan", 2, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Richardson", "S Dhawan", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Richardson", "S Dhawan", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Hastings", "Kohli", 2, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Hastings", "Kohli", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Hastings", "S Dhawan", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Hastings", "S Dhawan", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Hastings", "S Dhawan", 0, 0, 0, 0, 1);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Hastings", "Rahane", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Maxwell", "Kohli", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Maxwell", "Rahane", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Maxwell", "Kohli", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Maxwell", "Kohli", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Maxwell", "Rahane", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Maxwell", "Kohli", 1, 0, 0, 1, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Hastings", "Kohli", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Hastings", "Rahane", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Hastings", "Kohli", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Hastings", "Kohli", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Hastings", "Kohli", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Hastings", "Rahane", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Maxwell", "Kohli", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Maxwell", "Rahane", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Maxwell", "Rahane", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Maxwell", "Kohli", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Maxwell", "Rahane", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Maxwell", "Kohli", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Hastings", "Kohli", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Hastings", "Rahane", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Hastings", "Kohli", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Hastings", "Rahane", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Hastings", "Rahane", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Hastings", "Rahane", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Maxwell", "Kohli", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Maxwell", "Kohli", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Maxwell", "Kohli", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Maxwell", "Rahane", 2, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Maxwell", "Rahane", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Maxwell", "Rahane", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Faulkner", "Rahane", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Faulkner", "Kohli", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Faulkner", "Kohli", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Faulkner", "Rahane", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Faulkner", "Rahane", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Faulkner", "Rahane", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Maxwell", "Kohli", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Maxwell", "Rahane", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Maxwell", "Rahane", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Maxwell", "Kohli", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Maxwell", "Kohli", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Maxwell", "Rahane", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Faulkner", "Kohli", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Faulkner", "Kohli", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Faulkner", "Kohli", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Faulkner", "Kohli", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Faulkner", "Kohli", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Faulkner", "Rahane", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Boland", "Kohli", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Boland", "Kohli", 2, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Boland", "Kohli", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Boland", "Kohli", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Boland", "Rahane", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Boland", "Kohli", 2, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Faulkner", "Rahane", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Faulkner", "Rahane", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Faulkner", "Rahane", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Faulkner", "Rahane", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Faulkner", "Rahane", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Faulkner", "Rahane", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Boland", "Rahane", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Boland", "Rahane", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Boland", "Rahane", 2, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Boland", "Rahane", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Boland", "Rahane", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Boland", "Kohli", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Richardson", "Kohli", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Richardson", "Kohli", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Richardson", "Kohli", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Richardson", "Rahane", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Richardson", "Kohli", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Richardson", "Rahane", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Boland", "Kohli", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Boland", "Rahane", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Boland", "Rahane", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Boland", "Kohli", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Boland", "Rahane", 1, 0, 0, 1, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Boland", "Kohli", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Richardson", "Kohli", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Richardson", "Rahane", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Richardson", "Kohli", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Richardson", "Rahane", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Richardson", "Rahane", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Richardson", "Kohli", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Boland", "Rahane", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Boland", "Rahane", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Boland", "Rahane", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Boland", "Kohli", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Boland", "Rahane", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Boland", "Kohli", 2, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Richardson", "Rahane", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Richardson", "Rahane", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Richardson", "Kohli", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Richardson", "Kohli", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Richardson", "Rahane", 2, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Richardson", "Kohli", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Richardson", "Rahane", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Boland", "Rahane", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Boland", "Kohli", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Boland", "Rahane", 1, 0, 0, 1, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Boland", "Kohli", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Boland", "Rahane", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Boland", "Kohli", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Hastings", "Rahane", 2, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Hastings", "Rahane", 0, 0, 0, 0, 1);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Hastings", "Kohli", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Hastings", "Kohli", 2, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Hastings", "Kohli", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Hastings", "Kohli", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Faulkner", "Dhoni", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Faulkner", "Kohli", 1, 1, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Faulkner", "Kohli", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Faulkner", "Dhoni", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Faulkner", "Dhoni", 1, 1, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Faulkner", "Dhoni", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Faulkner", "Dhoni", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Faulkner", "Kohli", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Hastings", "Kohli", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Hastings", "Kohli", 0, 0, 0, 0, 1);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Hastings", "Gurkeerat Singh", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Hastings", "Gurkeerat Singh", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Hastings", "Gurkeerat Singh", 2, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Hastings", "Gurkeerat Singh", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Faulkner", "Gurkeerat Singh", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Faulkner", "Dhoni", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Faulkner", "Gurkeerat Singh", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Faulkner", "Gurkeerat Singh", 0, 0, 0, 0, 1);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Faulkner", "Jadeja", 2, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Faulkner", "Jadeja", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Hastings", "Jadeja", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Hastings", "Dhoni", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Hastings", "Dhoni", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Hastings", "Dhoni", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Hastings", "Dhoni", 0, 0, 0, 0, 1);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Hastings", "Jadeja", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Faulkner", "Jadeja", 2, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Faulkner", "R Dhawan", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Faulkner", "R Dhawan", 2, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Faulkner", "R Dhawan", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Faulkner", "Jadeja", 1, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Faulkner", "R Dhawan", 0, 0, 0, 0, 0);
INSERT INTO India(Bowler, Batsman, Runs, Wide, No_Ball, Leg_Bye, Wicket)		VALUES ("Faulkner", "R Dhawan", 0, 0, 0, 0, 0);
